spring:
  application:
    name: routes-provider
  datasource:
    url: jdbc:postgresql://${DEV_ENV_HOST}:5432/walking_routes_app_db
    username: ${DEV_ENV_DB_USER}
    password: ${DEV_ENV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  s3:
    bucket: ${DEV_ENV_S3_BUCKET}
    endpoint: ${DEV_ENV_S3_ENDPOINT}
    region: ${DEV_ENV_S3_REGION}
    access-key: ${DEV_ENV_S3_ACCESS_KEY}
    secret-key: ${DEV_ENV_S3_SECRET_KEY}

server:
  port: 8081

  logging:
    level:
      org:
        springframework:
          web: DEBUG
          data: DEBUG

radius-in-meters: 10000