spring:
  application:
    name: routes-provider
  datasource:
    url: jdbc:postgresql://${DEV_ENV_HOST}:5432/walking_routes_app_db
    username: ${DEV_ENV_DB_USER}
    password: ${DEV_ENV_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: 8081

  logging:
    level:
      org:
        springframework:
          web: DEBUG
          data: DEBUG

radius-in-meters: 10000