global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot'
    static_configs:
      - targets: ['192.168.65.254:8080', '192.168.65.254:8081', '192.168.65.254:8082', '192.168.65.254:8083']
    metrics_path: '/actuator/prometheus'
    scheme: 'http'
