name: Deploy

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Build JAR
        run: ./gradlew clean bootJar -x test

      - name: Verify JAR exists
        run: ls -la build/libs/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          load: true
          tags: user/data-provider:latest
          build-args: |
            DEV_ENV_HOST=${{ secrets.DEV_ENV_HOST }}
            DEV_ENV_DB_USER=${{ secrets.DEV_ENV_DB_USER }}
            DEV_ENV_DB_PASSWORD=${{ secrets.DEV_ENV_DB_PASSWORD }}
            SERVER_PORT=${{ secrets.SERVER_PORT }}

      - name: Deploy Docker container
        run: docker run -d --network walking_routes_network --name data-provider -e DEV_ENV_HOST=${{ secrets.DEV_ENV_HOST }} -e SERVER_PORT=${{ secrets.SERVER_PORT }} -e DEV_ENV_DB_USER=${{ secrets.DEV_ENV_DB_USER }} -e DEV_ENV_DB_PASSWORD=${{ secrets.DEV_ENV_DB_PASSWORD }} -p 28081:8081 user/data-provider:latest